services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SKIP_TESTS=true
    container_name: GOOSE_IDS
    command: streamlit run main.py --server.port=8080 --server.address=0.0.0.0
    # command: python classifier.py
    volumes: 
      - .:/app