services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SKIP_TESTS=true
    container_name: GOOSE_Attack_Detector
    command: streamlit run web.py --server.port=8080 --server.address=0.0.0.0
    volumes: 
      - .:/app